=== rherardi/pst2ical/pst2ical.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.gssnet.com/pst2ical"
	xmlns:tns="http://www.gssnet.com/pst2ical" version="1.0.0.0">

	<simpleType name="sourceType">
		<restriction base="string">
			<enumeration value="PST"></enumeration>
		</restriction>
	</simpleType>

	<simpleType name="targetType">
		<restriction base="string">
			<enumeration value="ICAL"></enumeration>
		</restriction>
	</simpleType>

	<simpleType name="languageType">
		<restriction base="ID">
			<enumeration value="en"></enumeration>
			<enumeration value="fr"></enumeration>
		</restriction>
	</simpleType>

	<simpleType name="settingType">
		<restriction base="ID">
			<enumeration value="FilterRegex"></enumeration>
			<enumeration value="FilterGroup"></enumeration>
			<enumeration value="PSTFilePassword"></enumeration>
			<enumeration value="MailHost"></enumeration>
			<enumeration value="Domain"></enumeration>
			<enumeration value="InputDir"></enumeration>
			<enumeration value="OutputDir"></enumeration>
			<enumeration value="LogDir"></enumeration>
			<enumeration value="LogSizeWrap"></enumeration>
			<enumeration value="SMTPAddressFile"></enumeration>
			<enumeration value="SMTPPartsSeparator"></enumeration>
		</restriction>
	</simpleType>

	<simpleType name="dateMaskType">
		<restriction base="string">
			<enumeration value="YYYYMMDDTHHMISS"></enumeration>
			<enumeration value="YYYYMMDDTHHMISSZ"></enumeration>
			<enumeration value="YYYYMMDDHHMISS"></enumeration>
		</restriction>
	</simpleType>

	<simpleType name="valueModifierType">
		<restriction base="string">
			<enumeration value="base64"></enumeration>
			<enumeration value="smtpLookup"></enumeration>
			<enumeration value="timezoneName"></enumeration>
			<enumeration value="16bytes"></enumeration>
		</restriction>
	</simpleType>

	<complexType name="conversionRuleType">
		<sequence>
			<element name="conversion" minOccurs="0" maxOccurs="unbounded">
				<complexType>
					<attribute name="input" type="string"></attribute>
					<attribute name="output" type="string"></attribute>
				</complexType>
			</element>
			<element name="default">
				<complexType>
					<attribute name="output" type="string"></attribute>
					<attribute name="fieldPresent" type="boolean" use="optional" default="false"></attribute>
				</complexType>
			</element>
		</sequence>
	</complexType>

	<simpleType name="conditionType">
		<restriction base="string">
			<enumeration value="CalendarHeader"></enumeration>
			<enumeration value="CalendarFooter"></enumeration>
			<enumeration value="EventFooter"></enumeration>
			<enumeration value="Meeting"></enumeration>
			<enumeration value="MeetingAttendee"></enumeration>
			<enumeration value="Appointment"></enumeration>
			<enumeration value="AllDayEvent"></enumeration>
			<enumeration value="Anniversary"></enumeration>
			<enumeration value="Reminder"></enumeration>
			<enumeration value="AttachmentPart"></enumeration>
		</restriction>
	</simpleType>

	<complexType name="calendarType">
		<sequence>
			<element name="calendarItem" minOccurs="1" maxOccurs="unbounded">
				<complexType>
					<sequence>
						<element name="pstItemProperty" minOccurs="0" maxOccurs="unbounded">
							<complexType>
								<sequence>
									<element name="conversionRule" type="tns:conversionRuleType" minOccurs="0" maxOccurs="1"></element>
								</sequence>
								<attributeGroup ref="tns:pstItemPropertyType"></attributeGroup>
							</complexType>
						</element>
						<element name="configSetting" minOccurs="0" maxOccurs="unbounded">
							<complexType>
								<attributeGroup ref="tns:pstItemPropertyType"></attributeGroup>
							</complexType>
						</element>
					</sequence>
					<attribute name="name" type="string" use="required"></attribute>
					<attribute name="value" type="string" use="required"></attribute>
					<attribute name="condition" type="tns:conditionType"
						use="optional">
					</attribute>
					<attribute name="conditionLotusDocField" type="string"
						use="optional">
					</attribute>
					<attribute name="conditionLotusDocFieldValue" type="string"
						use="optional">
					</attribute>
					<attribute name="numeric" type="boolean" use="optional" default="false">
					</attribute>
				</complexType>
			</element>
		</sequence>
		<attribute name="dateFilterProperty" type="string"
			use="optional" />
		<attribute name="dateFilterAfter" type="string"
			use="optional">
		</attribute>
		<attribute name="dateFilterBefore" type="string"
			use="optional">
		</attribute>
		<attribute name="dateMask" type="tns:dateMaskType"
			use="optional" />
	</complexType>

	<simpleType name="smtpAddressEmailPartType">
		<restriction base="string">
			<enumeration value="FirstName, LastName"></enumeration>
			<enumeration value="(F)irstName, LastName"></enumeration>
			<enumeration value="LastName, (F)irstName"></enumeration>
		</restriction>
	</simpleType>

	<simpleType name="smtpAddressEmailSeparatorType">
		<restriction base="string">
			<enumeration value="."></enumeration>
			<enumeration value="_"></enumeration>
			<enumeration value="none"></enumeration>
		</restriction>
	</simpleType>

	<attributeGroup name="pstItemPropertyType">
		<attribute name="name" type="string" use="required"></attribute>
		<attribute name="placeholder" type="string" use="required"></attribute>
		<attribute name="multivalue" type="boolean" use="optional"
			default="false">
		</attribute>
		<attribute name="dateMask" type="tns:dateMaskType"
			use="optional">
		</attribute>
		<attribute name="valueModifier" type="tns:valueModifierType"
			use="optional">
		</attribute>
		<attribute name="smtpPartsSeparator" type="string"
			use="optional">
		</attribute>
		<attribute name="smtpLookupRequired" type="boolean" use="optional"
			default="false">
		</attribute>
		<attribute name="binary" type="boolean" use="optional" default="false">
		</attribute>
		<attribute name="namedProperty" type="boolean" use="optional" default="false">
		</attribute>
	</attributeGroup>

	<complexType name="calendarConverterType">
		<sequence>
			<element name="configEntry" minOccurs="0" maxOccurs="unbounded">
				<complexType>
					<attribute name="setting" type="tns:settingType"></attribute>
					<attribute name="value" type="string" use="required"></attribute>
				</complexType>
			</element>
			<element name="calendar" minOccurs="1" maxOccurs="1" type="tns:calendarType"></element>
			<element name="smtpAddrEntry" minOccurs="0" maxOccurs="1">
				<complexType>
					<sequence>
						<element name="lotusDocField" minOccurs="0"
							maxOccurs="unbounded">
							<complexType>
								<attributeGroup
									ref="tns:pstItemPropertyType">
								</attributeGroup>
							</complexType>
						</element>
						<element name="configSetting" minOccurs="0"
							maxOccurs="unbounded">
							<complexType>
								<attributeGroup
									ref="tns:pstItemPropertyType">
								</attributeGroup>
							</complexType>
						</element>
					</sequence>
					<attribute name="file" type="string"
						use="required">
					</attribute>
					<attribute name="lotusPart" type="string"
						use="required">
					</attribute>
					<attribute name="emailPart"
						type="tns:smtpAddressEmailPartType" use="required">
					</attribute>
					<attribute name="emailSeparator"
						type="tns:smtpAddressEmailSeparatorType" use="required">
					</attribute>
					<attribute name="emailPreference"
						type="string" use="optional">
					</attribute>
					<attribute name="partsSeparator"
						type="string" use="required">
					</attribute>
				</complexType>
			</element>
		</sequence>
		<attribute name="source" type="tns:sourceType" use="required"></attribute>
		<attribute name="target" type="tns:targetType" use="required"></attribute>
		<attribute name="language" type="tns:languageType" use="required"></attribute>
	</complexType>
	<element name="calendarConverter" type="tns:calendarConverterType"></element>
</schema>

=== rherardi/pst2ical/pst2ical.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:calendarConverter source="PST" target="ICAL" language="en"
	xmlns:tns="http://www.gssnet.com/pst2ical"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.gssnet.com/pst2ical pst2ical.xsd ">

	<!-- Global configuration settings -->
	<configEntry setting="PSTFilePassword" value="" />
	<configEntry setting="InputDir" value="" />
	<configEntry setting="OutputDir" value="c:/converted" />
	<configEntry setting="LogDir" value="" />

	<configEntry setting="SMTPAddressFile" value="pst2ical.adr" />
	<configEntry setting="SMTPPartsSeparator" value="&lt;==&gt;" />

	<!-- Calendar formatting/conversion rules -->
	<calendar dateFilterProperty="PR_CLIENT_SUBMIT_TIME" dateFilterAfter="20080601000000" dateFilterBefore="20100303000000" dateMask="YYYYMMDDHHMISS">
		<calendarItem name="" value="BEGIN:VCALENDAR" condition="CalendarHeader" />
		<calendarItem name="PRODID" value="-//Microsoft Corporation//Outlook 11.0 MIMEDIR//EN" condition="CalendarHeader" />
		<calendarItem name="METHOD" value="PUBLISH" condition="CalendarHeader" />
		<calendarItem name="VERSION" value="2.0" condition="CalendarHeader" />
		<calendarItem name="BEGIN" value="VTIMEZONE" />
		<calendarItem name="TZID" value="{TZID}">
			<pstItemProperty name="0x825E" placeholder="{TZID}" valueModifier="timezoneName" namedProperty="true">
				<conversionRule>
					<!-- http://speleotrove.com/pmglobe/pmtimez.html -->
					<conversion input="FLE Standard Time" output="Europe/Vilnius"/>
					<conversion input="Pacific Standard Time" output="America/San Francisco"/>
					<conversion input="Central Standard Time" output="America/Chicago"/>
					<conversion input="Eastern Standard Time" output="America/New York"/>
					<default output=""/>
				</conversionRule>
			</pstItemProperty>
			<!--
			<lotusDocField name="StartTimeZone" placeholder="{TZID}" valueModifier="timezoneName">
				<conversionRule>
					<conversion input="Central" output="America/Chicago"/>
					<conversion input="Eastern" output="America/New York"/>
					<conversion input="Egypt" output="Africa/Cairo"/>
					<conversion input="Eire" output="Europe/Dublin"/>
					<conversion input="GMT" output="Europe/London"/>
					<conversion input="Iceland" output="Atlantic/Reykjavik"/>
					<conversion input="Japan" output="Asia/Tokyo"/>
					<conversion input="Libya" output="Africa/Tripoli"/>
					<conversion input="Mountain" output="America/Denver"/>
					<conversion input="Pacific" output="America/Los Angeles"/>
					<conversion input="Portugal" output="Europe/Lisbon"/>
					<conversion input="Turkey" output="Europe/Istanbul"/>
					<default output=""/>
				</conversionRule>
			</lotusDocField>
			-->
		</calendarItem>
		<calendarItem name="BEGIN" value="STANDARD" />
		<calendarItem name="DTSTART" value="19501105T020000" />
		<calendarItem name="TZOFFSETFROM" value="-0800" />
		<calendarItem name="TZOFFSETTO" value="-0800" />
		<calendarItem name="RRULE" value="FREQ=YEARLY;BYMINUTE=0;BYHOUR=2;BYDAY=-1SU;BYMONTH=10" />
		<calendarItem name="END" value="STANDARD" />
		<calendarItem name="BEGIN" value="DAYLIGHT" />
		<calendarItem name="DTSTART" value="19500326T020000" />
		<calendarItem name="TZOFFSETFROM" value="-0800" />
		<calendarItem name="TZOFFSETTO" value="-0800" />
		<calendarItem name="RRULE" value="FREQ=YEARLY;BYMINUTE=0;BYHOUR=2;BYDAY=-1SU;BYMONTH=10" />
		<calendarItem name="END" value="DAYLIGHT" />
		<calendarItem name="END" value="VTIMEZONE" />
		<calendarItem name="" value="BEGIN:VEVENT"/>
		<calendarItem name="TRANSP" value="OPAQUE"/>
		<calendarItem name="RRULE" value="FREQ={Frequency};INTERVAL={Interval};COUNT={Count}{BYDAYPrefix}{BYDAYValue}{BYMONTHDAYPrefix}{BYMONTHDAYValue}{BYDAYMONTHPrefix}{BYDAYMONTHValue}{BYMONTHPrefix}{BYMONTHValue}" conditionLotusDocField="Repeats" conditionLotusDocFieldValue="1">
			<!--
			<lotusDocField name="RepeatForUnit" placeholder="{Frequency}" >
				<conversionRule>
					<conversion input="D" output="DAILY"/>
					<conversion input="W" output="WEEKLY"/>
					<conversion input="M" output="MONTHLY"/>
					<conversion input="Y" output="YEARLY"/>
					<default output=""/>
				</conversionRule>
			</lotusDocField>
			<lotusDocField name="RepeatInterval" placeholder="{Interval}" >
			</lotusDocField>
			<lotusDocField name="RepeatFor" placeholder="{Count}" >
			</lotusDocField>
			<lotusDocField name="RepeatAdjust" placeholder="{BYDAYPrefix}" conditionLotusDocField="RepeatForUnit" conditionLotusDocFieldValue="W">
				<conversionRule>
					<default output=";BYDAY=" fieldPresent="true" />
				</conversionRule>
			</lotusDocField>
			<lotusDocField name="RepeatAdjust" placeholder="{BYDAYValue}" multivalue="true" onlyFirstValue="false" conditionLotusDocField="RepeatForUnit" conditionLotusDocFieldValue="W">
				<conversionRule>
					<conversion input="0" output="SU"/>
					<conversion input="1" output="MO"/>
					<conversion input="2" output="TU"/>
					<conversion input="3" output="WE"/>
					<conversion input="4" output="TH"/>
					<conversion input="5" output="FR"/>
					<conversion input="6" output="SA"/>
					<default output="" fieldPresent="true" />
				</conversionRule>
			</lotusDocField>
			<lotusDocField name="RepeatAdjust" placeholder="{BYMONTHDAYPrefix}" conditionLotusDocField="RepeatForUnit" conditionLotusDocFieldValue="M" dotPresentInValue="no">
				<conversionRule>
					<default output=";BYMONTHDAY=" fieldPresent="true" />
				</conversionRule>
			</lotusDocField>
			<lotusDocField name="RepeatAdjust" placeholder="{BYMONTHDAYValue}" multivalue="true" onlyFirstValue="false" conditionLotusDocField="RepeatForUnit" conditionLotusDocFieldValue="M" dotPresentInValue="no">
			</lotusDocField>
			<lotusDocField name="RepeatAdjust" placeholder="{BYDAYMONTHPrefix}" conditionLotusDocField="RepeatForUnit" conditionLotusDocFieldValue="M" dotPresentInValue="yes">
				<conversionRule>
					<default output=";BYDAY=" fieldPresent="true" />
				</conversionRule>
			</lotusDocField>
			<lotusDocField name="RepeatAdjust" placeholder="{BYDAYMONTHValue}" multivalue="true" onlyFirstValue="false" conditionLotusDocField="RepeatForUnit" conditionLotusDocFieldValue="M" dotPresentInValue="yes">
				<conversionRule>
					<conversion input="0" output="SU"/>
					<conversion input="1" output="MO"/>
					<conversion input="2" output="TU"/>
					<conversion input="3" output="WE"/>
					<conversion input="4" output="TH"/>
					<conversion input="5" output="FR"/>
					<conversion input="6" output="SA"/>
					<default output="" fieldPresent="true" />
				</conversionRule>
			</lotusDocField>
			<lotusDocField name="RepeatAdjust" placeholder="{BYMONTHPrefix}" conditionLotusDocField="RepeatForUnit" conditionLotusDocFieldValue="Y" dotPresentInValue="no">
				<conversionRule>
					<default output=";BYMONTH=" fieldPresent="true" />
				</conversionRule>
			</lotusDocField>
			<lotusDocField name="RepeatAdjust" placeholder="{BYMONTHValue}" multivalue="true" onlyFirstValue="false" conditionLotusDocField="RepeatForUnit" conditionLotusDocFieldValue="Y" dotPresentInValue="no">
			</lotusDocField>
			-->
		</calendarItem>

		<calendarItem name="CATEGORIES" value="{Categories}">
			<pstItemProperty name="Keywords" placeholder="{Categories}" namedProperty="true">
			</pstItemProperty>
			<!--
			<lotusDocField name="Categories" placeholder="{Categories}" >
				<conversionRule>
					<conversion input="H" output="Holiday"/>
					<conversion input="V" output="Vacation"/>
					<conversion input="P" output="Projects"/>
					<conversion input="C" output="Clients"/>
					<conversion input="PC" output="Phone Calls"/>
					<conversion input="T" output="Travel"/>
					<default output=""/>
				</conversionRule>
			</lotusDocField>
			-->
		</calendarItem>

		<calendarItem name="UID" value="{ApptUNID}">
			<pstItemProperty name="0x0023" placeholder="{ApptUNID}" valueModifier="16bytes" namedProperty="true">
			</pstItemProperty>
			<!--
			<lotusDocField name="ApptUNID" placeholder="{ApptUNID}" >
			</lotusDocField>
			-->
		</calendarItem>

		<calendarItem name="DTSTAMP" value="{Created}">
			<pstItemProperty name="PR_CREATION_TIME" placeholder="{Created}" dateMask="YYYYMMDDTHHMISSZ">
			</pstItemProperty>
			<!--
			<lotusDocField name="Created" placeholder="{Created}" dateMask="YYYYMMDDTHHMISSZ" >
			</lotusDocField>
			-->
		</calendarItem>

		<calendarItem name="SUMMARY" value="{Summary}">
			<pstItemProperty name="PR_SUBJECT" placeholder="{Summary}">
			</pstItemProperty>
			<!--
			<lotusDocField name="Subject" placeholder="{Summary}" >
			</lotusDocField>
			-->
		</calendarItem>

		<calendarItem name="" value="DTSTART:{Dtstart}">
			<pstItemProperty name="0x8516" placeholder="{Dtstart}" namedProperty="true">
			</pstItemProperty>
			<!--
			<lotusDocField name="StartDateTime" placeholder="{Dtstart}" dateMask="YYYYMMDDTHHMISSZ" >
			</lotusDocField>
			-->
		</calendarItem>

		<calendarItem name="" value="DTEND:{Dtend}">
			<pstItemProperty name="0x8517" placeholder="{Dtend}" namedProperty="true">
			</pstItemProperty>
			<!--
			<lotusDocField name="EndDateTime" placeholder="{Dtend}" dateMask="YYYYMMDDTHHMISSZ" >
			</lotusDocField>
			-->
		</calendarItem>

		<calendarItem name="LOCATION" value="{Location}">
			<pstItemProperty name="0x8208" placeholder="{Location}" namedProperty="true">
			</pstItemProperty>
			<!--
			<lotusDocField name="Location" placeholder="{Location}" >
			</lotusDocField>
			-->
		</calendarItem>

		<calendarItem name="DESCRIPTION" value="{Description}">
			<pstItemProperty name="PR_BODY" placeholder="{Description}">
			</pstItemProperty>
			<!--
			<lotusDocField name="Body" placeholder="{Description}" >
			</lotusDocField>
			-->
		</calendarItem>

		<calendarItem name="" value="ATTACH;ENCODING=BASE64;VALUE=BINARY;X-FILENAME={Filename}:" condition="AttachmentPart">
			<pstItemProperty name="PR_MESSAGE_ATTACHMENTS" placeholder="{Filename}">
			</pstItemProperty>
			<!--
